import { parseRulesMd, serializeRulesMd } from "../rules/parse";
import type { Rule } from "../config";
import type { CandidateRule } from "./synthesize";

export const RULES_MD_PREAMBLE = [
  "# Guardrails rules",
  "",
  "Rules Guardrails checks on every pull request. Edit freely.",
  "- Rules generated by `guardrails init` start as `status: suggested` and are NOT applied until you change them to `status: active`.",
  "- Format: `## <kebab-case-id>`, optional `scope:` (comma-separated globs), `severity:` (low|medium|high), `source:`, `status:` (active|suggested|disabled), a blank line, then the rule in plain language.",
  "- Text before the first `##` (like this) is ignored.",
].join("\n");

export interface MergeSuggestionsResult {
  /** Full new file contents (existing text untouched, new blocks appended). */
  text: string;
  added: Rule[];
  skipped: { id: string; reason: "id-exists" | "duplicate-text" }[];
}

const norm = (s: string) => s.toLowerCase().replace(/\s+/g, " ").trim();

/**
 * Appends candidates to an existing rules.md as `status: suggested`, WITHOUT touching anything
 * already in the file: existing text (user rules, `source: user`, comments, even invalid blocks)
 * stays byte-for-byte. Candidates whose id (or identical text) already exists in rules.md,
 * in config.json rules, or is disabled there are skipped.
 */
export function mergeSuggestions(
  existingMd: string | null | undefined,
  candidates: readonly CandidateRule[],
  opts: { configRules?: readonly Rule[]; disabledRules?: readonly string[] } = {},
): MergeSuggestionsResult {
  const existing = existingMd ? parseRulesMd(existingMd).rules : [];
  const known = [...existing, ...(opts.configRules ?? [])];
  // Ids of blocks that failed to parse are also reserved, so we never add a second block with that heading.
  const reservedIds = new Set([
    ...known.map((r) => r.id),
    ...(opts.disabledRules ?? []),
    ...[...(existingMd ?? "").matchAll(/^##[ \t]+([^\s#][^\n]*?)[ \t]*$/gm)].map((m) => m[1]!),
  ]);
  const texts = new Set(known.map((r) => norm(r.rule)));

  const added: Rule[] = [];
  const skipped: MergeSuggestionsResult["skipped"] = [];
  for (const c of candidates) {
    if (reservedIds.has(c.id)) {
      skipped.push({ id: c.id, reason: "id-exists" });
      continue;
    }
    if (texts.has(norm(c.rule))) {
      skipped.push({ id: c.id, reason: "duplicate-text" });
      continue;
    }
    reservedIds.add(c.id);
    texts.add(norm(c.rule));
    added.push({
      id: c.id,
      rule: c.rule,
      scope: c.scope,
      severity: c.severity,
      // "user" is reserved for rules the user wrote; never let generated rules claim it.
      source: c.source === "user" ? "inferred" : c.source,
      status: "suggested",
    });
  }

  if (!added.length) return { text: existingMd ?? "", added, skipped };
  const blocks = serializeRulesMd(added);
  const base = existingMd?.trim() ? existingMd.replace(/\s+$/, "") + "\n\n" : RULES_MD_PREAMBLE + "\n\n";
  return { text: base + blocks, added, skipped };
}
